# .NET Core
# Build and test projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- core-3

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  Major: '2'
  Minor: '0'
  Patch: $[counter('myversioncounter', 0)]

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview6-012264'
    
- script: dotnet build -c $(buildConfiguration) Collections.Pooled/Collections.Pooled.csproj /p:Version=$(Major).$(Minor)-preview.$(Patch)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test -c $(buildConfiguration) --logger trx Collections.Pooled.Tests/Collections.Pooled.Tests.csproj
  displayName: 'dotnet test'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet pack -c $(buildConfiguration) --no-build /p:PackageVersion=$(Major).$(Minor)-preview.$(Patch) Collections.Pooled/Collections.Pooled.csproj
  displayName: 'dotnet pack'
- task: NuGetCommand@2
  displayName: 'nuget publish'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGet'
    packagesToPush: 'Collections.Pooled/bin/$(buildConfiguration)/*.nupkg;!Collections.Pooled/bin/$(buildConfiguration)/*.symbols.nupkg'
